<a href="https://colab.research.google.com/github/ribka-5/Statistika-Sains-Data/blob/main/Jurnal2_SSD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()

Saving USvideos.csv to USvideos.csv

1. Load dataset tersebut menggunakan pandas

In [ ]:
df = pd.read_csv('USvideos.csv')
df.head(15)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
5,gHZ1Qz0KiKM,17.14.11,2 Weeks with iPhone X,iJustine,28,2017-11-13T19:07:23.000Z,"ijustine|""week with iPhone X""|""iphone x""|""appl...",119180,9763,511,1434,https://i.ytimg.com/vi/gHZ1Qz0KiKM/default.jpg,False,False,False,Using the iPhone for the past two weeks -- her...
6,39idVpFF7NQ,17.14.11,Roy Moore & Jeff Sessions Cold Open - SNL,Saturday Night Live,24,2017-11-12T05:37:17.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",2103417,15993,2445,1970,https://i.ytimg.com/vi/39idVpFF7NQ/default.jpg,False,False,False,Embattled Alabama Senate candidate Roy Moore (...
7,nc99ccSXST0,17.14.11,5 Ice Cream Gadgets put to the Test,CrazyRussianHacker,28,2017-11-12T21:50:37.000Z,"5 Ice Cream Gadgets|""Ice Cream""|""Cream Sandwic...",817732,23663,778,3432,https://i.ytimg.com/vi/nc99ccSXST0/default.jpg,False,False,False,Ice Cream Pint Combination Lock - http://amzn....
8,jr9QtXwC9vc,17.14.11,The Greatest Showman | Official Trailer 2 [HD]...,20th Century Fox,1,2017-11-13T14:00:23.000Z,"Trailer|""Hugh Jackman""|""Michelle Williams""|""Za...",826059,3543,119,340,https://i.ytimg.com/vi/jr9QtXwC9vc/default.jpg,False,False,False,"Inspired by the imagination of P.T. Barnum, Th..."
9,TUmyygCMMGA,17.14.11,Why the rise of the robots won’t mean the end ...,Vox,25,2017-11-13T13:45:16.000Z,"vox.com|""vox""|""explain""|""shift change""|""future...",256426,12654,1363,2368,https://i.ytimg.com/vi/TUmyygCMMGA/default.jpg,False,False,False,"For now, at least, we have better things to wo..."
10,9wRQljFNDW8,17.14.11,Dion Lewis' 103-Yd Kick Return TD vs. Denver! ...,NFL,17,2017-11-13T02:05:26.000Z,"NFL|""Football""|""offense""|""defense""|""afc""|""nfc""...",81377,655,25,177,https://i.ytimg.com/vi/9wRQljFNDW8/default.jpg,False,False,False,New England Patriots returner Dion Lewis blast...
11,VifQlJit6A0,17.14.11,(SPOILERS) 'Shiva Saves the Day' Talked About ...,amc,24,2017-11-13T03:00:00.000Z,"The Walking Dead|""shiva""|""tiger""|""king ezekiel...",104578,1576,303,1279,https://i.ytimg.com/vi/VifQlJit6A0/default.jpg,False,False,False,Shiva arrives just in time as King Ezekiel att...
12,5E4ZBSInqUU,17.14.11,Marshmello - Blocks (Official Music Video),marshmello,10,2017-11-13T17:00:00.000Z,"marshmello|""blocks""|""marshmello blocks""|""block...",687582,114188,1333,8371,https://i.ytimg.com/vi/5E4ZBSInqUU/default.jpg,False,False,False,WATCH SILENCE MUSIC VIDEO ▶ https://youtu.be/T...
13,GgVmn66oK_A,17.14.11,Which Countries Are About To Collapse?,NowThis World,25,2017-11-12T14:00:00.000Z,"nowthis|""nowthis world""|""world news""|""nowthis ...",544770,7848,1171,3981,https://i.ytimg.com/vi/GgVmn66oK_A/default.jpg,False,False,False,"The world at large is improving, but some coun..."
14,TaTleo4cOs8,17.14.11,SHOPPING FOR NEW FISH!!!,The king of DIY,15,2017-11-12T18:30:01.000Z,"shopping for new fish|""new fish""|""aquarium fis...",207532,7473,246,2120,https://i.ytimg.com/vi/TaTleo4cOs8/default.jpg,False,False,False,Today we go shopping for new fish for some of ...

In [ ]:
df.tail(15)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
40934,Qcj15vHJTtk,18.14.06,Royal Wedding - SNL,Saturday Night Live,24,2018-05-20T04:58:51.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""SNL...",8607264,66559,14179,8382,https://i.ytimg.com/vi/Qcj15vHJTtk/default.jpg,False,False,False,Footage from Prince Harry's (Mikey Day) weddin...
40935,2in8XqiElwc,18.14.06,Nicki Minaj - Chun-Li (Live on SNL / 2018),NickiMinajAtVEVO,10,2018-05-20T07:53:59.000Z,"Nicki Minaj new music|""Nicki Minaj Queen""|""Nic...",4945185,189265,9406,18683,https://i.ytimg.com/vi/2in8XqiElwc/default.jpg,False,False,False,Chun-Li (Live on SNL / 2018)Song Available Her...
40936,Xr2rgT9uEnA,18.14.06,LIE DETECTOR TEST WITH MY GIRLFRIEND!,miniminter,20,2018-05-20T18:00:02.000Z,"miniminter|""mm7games""|""simon""|""random""|""lie de...",3229540,109945,3062,6774,https://i.ytimg.com/vi/Xr2rgT9uEnA/default.jpg,False,False,False,Talia: https://www.youtube.com/user/nataliahad...
40937,v7H_Or9Nr5I,18.14.06,Lucas the Spider - Giant Spider,Lucas the Spider,1,2018-05-19T14:52:43.000Z,"LucastheSpider|""Animation""|""3D Animation""|""Cute""",8300584,266267,4237,14617,https://i.ytimg.com/vi/v7H_Or9Nr5I/default.jpg,False,False,False,Lucas is a tiny spider to some...giant arachni...
40938,n_W54baizX8,18.14.06,Daddy Yankee - Hielo (Video Oficial),Daddy Yankee,10,2018-05-18T14:00:04.000Z,"daddy yankee reggaeton|""daddy yankee youtube""|...",41803845,628861,42833,39363,https://i.ytimg.com/vi/n_W54baizX8/default.jpg,False,False,False,Daddy Yankee - Hielo (Video Oficial)Spotify: h...
40939,pcJo0tIWybY,18.14.06,SZA - Garden (Say It Like Dat) (Official Video),SZAVEVO,10,2018-05-18T14:00:04.000Z,"Garden (Say It Like Dat)|""R&B""|""SZA""|""Top Dawg...",6004782,210802,4166,15169,https://i.ytimg.com/vi/pcJo0tIWybY/default.jpg,False,False,False,SZA's CTRL available on:Apple Music - http://s...
40940,_QWZvU7VCn8,18.14.06,Brad Pitt Bid $120k For A Night With Emilia Cl...,The Graham Norton Show,24,2018-05-18T17:13:08.000Z,"Graham Norton|""Graham Norton Show Official""|""E...",5564576,46351,2295,2861,https://i.ytimg.com/vi/_QWZvU7VCn8/default.jpg,False,False,False,Check out all that Emilia Clarke merch... Subs...
40941,7UoP9ABJXGE,18.14.06,Dan + Shay - Speechless (Wedding Video),Dan And Shay,10,2018-05-18T04:04:58.000Z,"wedding video|""heartfelt wedding video""|""emoti...",5534278,45128,1591,806,https://i.ytimg.com/vi/7UoP9ABJXGE/default.jpg,False,False,False,Stream + Download:https://wmna.sh/speechlessht...
40942,ju_inUnrLc4,18.14.06,Fifth Harmony - Don't Say You Love Me,FifthHarmonyVEVO,10,2018-05-18T07:00:08.000Z,"fifth hamony|""harmonizers""|""lauren""|""ally""|""no...",23502572,676467,15993,52432,https://i.ytimg.com/vi/ju_inUnrLc4/default.jpg,False,False,False,Fifth Harmony available at iTunes http://smart...
40943,1PhPYr_9zRY,18.14.06,BTS Plays With Puppies While Answering Fan Que...,BuzzFeed Celeb,22,2018-05-18T16:39:29.000Z,"BuzzFeed|""BuzzFeedVideo""|""Puppy Interview""|""pu...",8259128,645888,4052,62610,https://i.ytimg.com/vi/1PhPYr_9zRY/default.jpg,False,False,False,"BTS with the PPS, the puppies. These adorable ..."
40944,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals
40945,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN
40946,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...
40947,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...
40948,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...

2. Ambil secara acak 1% dari data kemudian hitung:

In [ ]:
df1 = df.sample(frac=0.01)[['likes', 'dislikes', 'views']]
df1

       likes  dislikes    views
23199   5953       287   208634
32103   9614       190   285887
29826   9293       281   806795
2673   71238      1114  1307208
34047  33131       310   765442
...      ...       ...      ...
19604   6288       153   146065
28708  15428       628   806290
13327   9999       347   177893
24720  72871      2400  1871078
17814   6084       536   263220

[409 rows x 3 columns]

a. rata rata likes,dislikes dan views dari sampel

In [ ]:
df1.mean()

likes       6.505356e+04
dislikes    2.502609e+03
views       2.041487e+06
dtype: float64

b. varians likes,dislikes dan views sampel

In [ ]:
df1.var()

likes       2.465399e+10
dislikes    4.935784e+07
views       2.907477e+13
dtype: float64

3. a)Ambil data video dengan jumlah dislike lebih dari 10 persen jumlah like dengan cara: query()

In [ ]:
df2 = df1.query('dislikes > 0.1* likes')
df2

       likes  dislikes    views
13441    260        31    62484
39843   6182      1896   738009
33139  16526     13340  1519621
1598     125        16    36414
12803  11383     12122   635686
...      ...       ...      ...
2078   22530      5069  1921050
15659   3075       702   225051
17970   2787       322   107574
12441   3626       446  1139228
21018    429       658   156905

[75 rows x 3 columns]

3. b) Ambil data video dengan jumlah dislike lebih dari 10 persen jumlah like dengan cara: boolean indexing

In [ ]:
df1[df1['dislikes'] > 0.1 * df1['likes']]

       likes  dislikes    views
13441    260        31    62484
39843   6182      1896   738009
33139  16526     13340  1519621
1598     125        16    36414
12803  11383     12122   635686
...      ...       ...      ...
2078   22530      5069  1921050
15659   3075       702   225051
17970   2787       322   107574
12441   3626       446  1139228
21018    429       658   156905

[75 rows x 3 columns]

4. Dari query nomor 3, bandingkan ratio like dan dislike nya kemudian urutkan berdasarkan
ratio terbesar

In [ ]:
df3 = df2.assign(ratio = df2['likes'] / (df['likes'] + df2['dislikes']))
df3 = df3.sort_values('ratio',ascending=False)
df3

       likes  dislikes    views     ratio
13177     29         3     2917  0.906250
27117  28279      2944  2996112  0.905711
28305  16327      1762   553214  0.902593
8822    3928       425   227928  0.902366
30791   2261       248   819451  0.901156
...      ...       ...      ...       ...
12803  11383     12122   635686  0.484280
312     2133      2483  1015189  0.462088
10292    580       752    89516  0.435435
21018    429       658   156905  0.394664
19955    195       677    22871  0.223624

[75 rows x 4 columns]

5. Buat kolom Baru pada dataframe sampel, yaitu label, dimana label bernilai 1 jika ratio <
rata-rata ratio dan 0 jika >= rata rata ratio dengan menggunakan .where() dan .loc !

In [ ]:
df3 = df3.assign(label = np.zeros_like(df3['likes'].values))
df3

       likes  dislikes    views     ratio  label
13177     29         3     2917  0.906250      0
27117  28279      2944  2996112  0.905711      0
28305  16327      1762   553214  0.902593      0
8822    3928       425   227928  0.902366      0
30791   2261       248   819451  0.901156      0
...      ...       ...      ...       ...    ...
12803  11383     12122   635686  0.484280      0
312     2133      2483  1015189  0.462088      0
10292    580       752    89516  0.435435      0
21018    429       658   156905  0.394664      0
19955    195       677    22871  0.223624      0

[75 rows x 5 columns]

In [ ]:
df3.loc[df1.where(df3['ratio'] >= df3['ratio'].mean()).dropna().index, 'label'] = 1

In [ ]:
df3

       likes  dislikes    views     ratio  label
13177     29         3     2917  0.906250      1
27117  28279      2944  2996112  0.905711      1
28305  16327      1762   553214  0.902593      1
8822    3928       425   227928  0.902366      1
30791   2261       248   819451  0.901156      1
...      ...       ...      ...       ...    ...
12803  11383     12122   635686  0.484280      0
312     2133      2483  1015189  0.462088      0
10292    580       752    89516  0.435435      0
21018    429       658   156905  0.394664      0
19955    195       677    22871  0.223624      0

[75 rows x 5 columns]

In [ ]:
df3.query('label == 1')

        likes  dislikes    views     ratio  label
13177      29         3     2917  0.906250      1
27117   28279      2944  2996112  0.905711      1
28305   16327      1762   553214  0.902593      1
8822     3928       425   227928  0.902366      1
30791    2261       248   819451  0.901156      1
17395     865        96    43367  0.900104      1
14125   10992      1232   779550  0.899215      1
12151    4747       535   676273  0.898713      1
5418    22758      2591  1722301  0.897787      1
2678    10985      1255  1042089  0.897467      1
27679   27321      3149  4777734  0.896652      1
17970    2787       322   107574  0.896430      1
17080     371        44    97478  0.893976      1
13547    3143       373   145745  0.893914      1
14696   41011      4874  2192207  0.893778      1
13441     260        31    62484  0.893471      1
16669     605        74    74307  0.891016      1
12441    3626       446  1139228  0.890472      1
12160       8         1     4168  0.888889      1
1598      125        16    36414  0.886525      1
4623     8303      1079  1188917  0.884993      1
21247     191        25    21180  0.884259      1
39909    2296       308   649426  0.881720      1
34178   17072      2293  1586426  0.881590      1
905       119        16    30873  0.881481      1
14342    3385       456   599843  0.881281      1
31876    2505       344   277012  0.879256      1
6836      115        16     8945  0.877863      1
17025    3055       435   281974  0.875358      1
9469     2782       397   253889  0.875118      1
11054     430        62    56842  0.873984      1
21154    9489      1373  1392938  0.873596      1
40718   32886      4838  5918752  0.871753      1
27565   12060      1823   497159  0.868688      1
27483   47849      7268  3680741  0.868135      1
15939      79        12    21913  0.868132      1
9439    19763      3135   935954  0.863088      1
34590   15825      2577   779028  0.859961      1
8951     9892      1711  1207371  0.852538      1
13722  149639     28559  1918104  0.839734      1
33401  176018     35861  7051346  0.830748      1
22599   71829     15899  5846111  0.818769      1
2078    22530      5069  1921050  0.816334      1
15659    3075       702   225051  0.814138      1
15128    1272       291  4924380  0.813820      1
33888   17006      4006   696529  0.809347      1
11561      20         5     2691  0.800000      1
23510    5660      1481   369067  0.792606      1

In [ ]:
df3.query('label == 0')

        likes  dislikes    views     ratio  label
8145     6182      1693  1321517  0.785016      0
13817    3091       847   369007  0.784916      0
1574        7         2    13659  0.777778      0
10031     162        48    19238  0.771429      0
39843    6182      1896   738009  0.765288      0
15861    9415      3032   669263  0.756407      0
36046    7262      2370  6504837  0.753945      0
31636  121980     39885  4365071  0.753591      0
32069  125244     42051  4610501  0.748642      0
20477     407       157    49151  0.721631      0
14610    1937       759   105477  0.718472      0
30869   22356      9067  1233934  0.711453      0
13228    2704      1103   364250  0.710271      0
522        23        10    36859  0.696970      0
11736  136078     64906  7500652  0.677059      0
2680     2477      1184   524511  0.676591      0
19925   15609      8678   648641  0.642690      0
15074    3053      1858   227226  0.621666      0
7676    11578      8786  1010286  0.568552      0
23108    1993      1592   569464  0.555927      0
33139   16526     13340  1519621  0.553338      0
21084    2724      2695   152157  0.502676      0
12803   11383     12122   635686  0.484280      0
312      2133      2483  1015189  0.462088      0
10292     580       752    89516  0.435435      0
21018     429       658   156905  0.394664      0
19955     195       677    22871  0.223624      0

6. Temukan video yang memiliki likes = 0 ! berapakah views maksimum nya ?

In [ ]:
df3 = df.query('likes == 0')
df3[['views', 'likes', 'dislikes']].describe()

              views  likes    dislikes
count  1.720000e+02  172.0  172.000000
mean   4.052518e+06    0.0    0.029070
std    1.135538e+07    0.0    0.274178
min    1.456000e+03    0.0    0.000000
25%    7.713425e+04    0.0    0.000000
50%    4.290240e+05    0.0    0.000000
75%    1.012722e+06    0.0    0.000000
max    5.611196e+07    0.0    3.000000

In [ ]:
df3.sort_values('views', ascending = False)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
18150,BhIEIO0vaBE,18.14.02,To Our Daughter,Kylie Jenner,22,2018-02-04T20:27:38.000Z,"Kylie Jenner|""Kylie""|""Travis Scott""|""Baby""|""An...",56111957,0,0,0,https://i.ytimg.com/vi/BhIEIO0vaBE/default.jpg,True,True,False,Directed by Tyler Ross @wttyler\nMusic by Jaco...
17916,BhIEIO0vaBE,18.13.02,To Our Daughter,Kylie Jenner,22,2018-02-04T20:27:38.000Z,"Kylie Jenner|""Kylie""|""Travis Scott""|""Baby""|""An...",55063465,0,0,0,https://i.ytimg.com/vi/BhIEIO0vaBE/default.jpg,True,True,False,Directed by Tyler Ross @wttyler\nMusic by Jaco...
17716,BhIEIO0vaBE,18.12.02,To Our Daughter,Kylie Jenner,22,2018-02-04T20:27:38.000Z,"Kylie Jenner|""Kylie""|""Travis Scott""|""Baby""|""An...",54454945,0,0,0,https://i.ytimg.com/vi/BhIEIO0vaBE/default.jpg,True,True,False,Directed by Tyler Ross @wttyler\nMusic by Jaco...
17496,BhIEIO0vaBE,18.11.02,To Our Daughter,Kylie Jenner,22,2018-02-04T20:27:38.000Z,"Kylie Jenner|""Kylie""|""Travis Scott""|""Baby""|""An...",53183123,0,0,0,https://i.ytimg.com/vi/BhIEIO0vaBE/default.jpg,True,True,False,Directed by Tyler Ross @wttyler\nMusic by Jaco...
17286,BhIEIO0vaBE,18.10.02,To Our Daughter,Kylie Jenner,22,2018-02-04T20:27:38.000Z,"Kylie Jenner|""Kylie""|""Travis Scott""|""Baby""|""An...",51243149,0,0,0,https://i.ytimg.com/vi/BhIEIO0vaBE/default.jpg,True,True,False,Directed by Tyler Ross @wttyler\nMusic by Jaco...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,aLSG3178eD4,17.03.12,Tell Hollywood to stand with immigrants,Define American,29,2017-11-28T13:00:35.000Z,"DACA|""black panther""",2093,0,0,0,https://i.ytimg.com/vi/aLSG3178eD4/default.jpg,True,True,False,"Undocumented in Hollywood? Yes, and we are #He..."
12492,VoUEz9yQJ8w,18.17.01,RAPID EYE MOVEMENT⎪Teaser Trailer,Tentmaker Pictures,1,2018-01-16T14:12:35.000Z,"Francois Arnaud|""Peter Bishai""|""sleep deprivat...",2068,0,0,1,https://i.ytimg.com/vi/VoUEz9yQJ8w/default.jpg,False,True,False,"From Director Peter Bishai (Colors of Heaven),..."
3776,aLSG3178eD4,17.02.12,Tell Hollywood to stand with immigrants,Define American,29,2017-11-28T13:00:35.000Z,"DACA|""black panther""",2005,0,0,0,https://i.ytimg.com/vi/aLSG3178eD4/default.jpg,True,True,False,"Undocumented in Hollywood? Yes, and we are #He..."
3543,aLSG3178eD4,17.01.12,Tell Hollywood to stand with immigrants,Define American,29,2017-11-28T13:00:35.000Z,"DACA|""black panther""",1873,0,0,0,https://i.ytimg.com/vi/aLSG3178eD4/default.jpg,True,True,False,"Undocumented in Hollywood? Yes, and we are #He..."
3313,aLSG3178eD4,17.30.11,Tell Hollywood to stand with immigrants,Define American,29,2017-11-28T13:00:35.000Z,"DACA|""black panther""",1456,0,0,0,https://i.ytimg.com/vi/aLSG3178eD4/default.jpg,True,True,False,"Undocumented in Hollywood? Yes, and we are #He..."

7. Jelaskan mengapa ada views yang sangat tinggi tetapi likes = 0

In [ ]:
df.query('ratings_disabled == True').describe()

       category_id         views  likes  dislikes  comment_count
count   169.000000  1.690000e+02  169.0     169.0     169.000000
mean     18.384615  4.124415e+06    0.0       0.0     412.106509
std       8.812869  1.144330e+07    0.0       0.0    1075.762958
min       1.000000  1.456000e+03    0.0       0.0       0.000000
25%      10.000000  8.583300e+04    0.0       0.0       0.000000
50%      22.000000  4.594910e+05    0.0       0.0       0.000000
75%      24.000000  1.015005e+06    0.0       0.0     179.000000
max      29.000000  5.611196e+07    0.0       0.0    5286.000000

In [ ]:
df.query('ratings_disabled == False and likes == 0')

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
192,wRGldR_SQAA,17.14.11,Apple Clips sample,Steve Kovach,22,2017-11-09T18:01:04.000Z,[none],2259,0,0,0,https://i.ytimg.com/vi/wRGldR_SQAA/default.jpg,False,False,False,Clips 2.0 lets you use augmented reality and s...
1490,A_mlvG_nRsg,17.21.11,Kelly Oubre Punches John Wall in the Lead duri...,Rob Andretti,17,2017-10-28T11:15:14.000Z,[none],2197,0,2,0,https://i.ytimg.com/vi/A_mlvG_nRsg/default.jpg,False,False,False,I'm BACK! \n\n• Will you be apart of the take ...
1741,A_mlvG_nRsg,17.22.11,Kelly Oubre Punches John Wall in the Lead duri...,Rob Andretti,17,2017-10-28T11:15:14.000Z,[none],2447,0,3,1,https://i.ytimg.com/vi/A_mlvG_nRsg/default.jpg,False,False,False,I'm BACK! \n\n• Will you be apart of the take ...

8. Berapa presentase video dengan likes lebih banyak dari dislikes dengan video likes lebih sedikit
dari dislikes ?

In [ ]:
p1 = '(likes > dislikes)'
p2 = '(likes < dislikes)'
dfp1 = df.query(p1)
dfp1

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40944,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals
40945,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN
40946,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...
40947,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...
40948,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...

In [ ]:
dfp2 = df.query(p2)
dfp2

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
43,0tO_l_Ed5Rs,17.14.11,Matthew Santoro - FACTS (Official Music Video)...,MatthewSantoro,10,2017-11-11T16:00:01.000Z,"matthew santoro facts|""music video""|""matthew s...",328330,15186,15448,7484,https://i.ytimg.com/vi/0tO_l_Ed5Rs/default.jpg,False,False,False,LISTEN WITH HEADPHONES! 🎧. WATCH IN 4K! 👀\nPro...
47,sbcbvuitiTc,17.14.11,Stephon Marbury and Jimmer Fredette fight in C...,NBA Highlights · YouTube,17,2017-11-10T18:23:05.000Z,"NBA|""Basketball""|""Sports""",956169,2017,2425,1447,https://i.ytimg.com/vi/sbcbvuitiTc/default.jpg,False,False,False,NaN
75,k8NxqyGcZA4,17.14.11,Rosie O’Donnell On Donald Trump’s Hostility To...,Watch What Happens Live with Andy Cohen,24,2017-11-10T12:59:55.000Z,"What What Happens live|""reality""|""interview""|""...",238643,2429,5381,2325,https://i.ytimg.com/vi/k8NxqyGcZA4/default.jpg,False,False,False,Rosie O’Donnell doesn’t hold back about Donald...
133,X7flefV8tec,17.14.11,"President Bill Clinton On Dictators, Democracy...",Team Coco,24,2017-11-09T02:37:49.000Z,[none],366180,4364,4448,1997,https://i.ytimg.com/vi/X7flefV8tec/default.jpg,False,False,False,#ConanNYC Highlight: President Clinton talks a...
169,bhoFXkVy8JA,17.14.11,Basmati Blues - Trailer,Blockbuster,1,2017-10-13T08:20:03.000Z,"Blockbuster|""blockbuster.dk""|""blockbuster.se""|...",12609,40,79,17,https://i.ytimg.com/vi/bhoFXkVy8JA/default.jpg,False,False,False,Basmati Blues - Trailer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39968,GnGPAYvve1A,18.10.06,#ProudToCreate: Pride 2018,YouTube Spotlight,24,2018-06-07T19:08:51.000Z,"#Pride|""#ProudToCreate""|""#ProudToBe""|""#ProudTo...",1227495,46556,121865,87199,https://i.ytimg.com/vi/GnGPAYvve1A/default.jpg,False,False,False,You don't just imagine a better future – you c...
40171,GnGPAYvve1A,18.11.06,#ProudToCreate: Pride 2018,YouTube Spotlight,24,2018-06-07T19:08:51.000Z,"#Pride|""#ProudToCreate""|""#ProudToBe""|""#ProudTo...",1253843,47073,123424,88066,https://i.ytimg.com/vi/GnGPAYvve1A/default.jpg,False,False,False,You don't just imagine a better future – you c...
40388,GnGPAYvve1A,18.12.06,#ProudToCreate: Pride 2018,YouTube Spotlight,24,2018-06-07T19:08:51.000Z,"#Pride|""#ProudToCreate""|""#ProudToBe""|""#ProudTo...",1291035,47762,125583,89296,https://i.ytimg.com/vi/GnGPAYvve1A/default.jpg,False,False,False,You don't just imagine a better future – you c...
40597,GnGPAYvve1A,18.13.06,#ProudToCreate: Pride 2018,YouTube Spotlight,24,2018-06-07T19:08:51.000Z,"#Pride|""#ProudToCreate""|""#ProudToBe""|""#ProudTo...",1315418,48135,126480,89956,https://i.ytimg.com/vi/GnGPAYvve1A/default.jpg,False,False,False,You don't just imagine a better future – you c...
40809,GnGPAYvve1A,18.14.06,#ProudToCreate: Pride 2018,YouTube Spotlight,24,2018-06-07T19:08:51.000Z,"#Pride|""#ProudToCreate""|""#ProudToBe""|""#ProudTo...",1329391,48386,126931,90365,https://i.ytimg.com/vi/GnGPAYvve1A/default.jpg,False,False,False,You don't just imagine a better future – you c...

In [ ]:
presentase = lambda L: list(map(lambda x:x/sum(L),(L)))
re = [dfp1.shape[0], dfp2.shape[0]]

print(presentase(re))

[0.9858712715855573, 0.0141287284144427]

9. Bagaimana perbandingan rata rata dan standard deviasi jumlah views antara video dengan
likes lebih banyak dari dislikes dengan video likes lebih sedikit dari dislikes ?

In [ ]:
r1 = dfp1.loc[:, 'views'].mean()
st1 = dfp1.loc[:, 'views'].std()

In [ ]:
r2 = dfp2.loc[:, 'views'].mean()
st2 = dfp2.loc[:, 'views'].std()

In [ ]:
print(presentase([r1, r2]))

[0.6936325660781124, 0.3063674339218876]

In [ ]:
print(presentase([st1, st2]))

[0.6525291274590552, 0.3474708725409449]

10. Bagaimana perbandingan rata rata dan standard deviasi jumlah comment antara video den-
gan likes lebih banyak dari dislikes dengan video likes lebih sedikit dari dislikes ?

In [ ]:
r1 = dfp1.loc[:, 'comment_count'].mean()
st1 = dfp1.loc[:, 'comment_count'].std()

In [ ]:
r2 = dfp2.loc[:, 'comment_count'].mean()
st2 = dfp2.loc[:, 'comment_count'].std()

In [ ]:
print(presentase([r1, r2]))

[0.348787682929341, 0.6512123170706591]

In [ ]:
print(presentase([st1, st2]))

[0.2269874820781621, 0.773012517921838]

11. Berapa ratio rata-rata jumlah likes/dislikes untuk video dengan komentar yang dinonaktifkan
?

In [ ]:
df4 = df.query('comments_disabled == True')
df4 = df4.assign(ratio = df4['likes']/ (df4['likes']+ df4['dislikes']))

In [ ]:
r1 = df4['ratio'].mean()

In [ ]:
print(r1, 1-r1, sep=':')

0.8324019250989896:0.16759807490101042

12. Berapa ratio rata-rata jumlah comments/views untuk video dengan ratings yang dinonak-
tifkan ?

In [ ]:
df5 = df.query('ratings_disabled == True')
df5 = df5.assign(ratio = df5['comment_count']/ (df5['views'] + df5['comment_count']))

In [ ]:
r1 = df5['ratio'].mean()

In [ ]:
print(r1, 1-r1)

0.0018133621624128007 0.9981866378375872

13. Berapa rata-rata jumlah views untuk video yang tidak memiliki tags ?

In [ ]:
df.query('tags=="[none]"')['views'].mean()

1494136.3687296417

14. Lakukan query untuk menentukan jumlah perbandingan rata-rata viewers yang tidak
melakukan rating like/dislike dengan yang meninggalkan ratings like/dislike

In [ ]:
df['views']

0          748374
1         2418783
2         3191434
3          343168
4         2095731
           ...
40944     1685609
40945     1064798
40946     1066451
40947     5660813
40948    10306119
Name: views, Length: 40949, dtype: int64

In [ ]:
df['likes'] + df['dislikes']

0         60493
1        103331
2        151372
3         10838
4        134224
          ...
40944     39545
40945     60390
40946     49100
40947    195803
40948    570055
Length: 40949, dtype: int64

In [ ]:
df['views'] - (df['likes'] + df['dislikes'])

0         687881
1        2315452
2        3040062
3         332330
4        1961507
          ...
40944    1646064
40945    1004408
40946    1017351
40947    5465010
40948    9736064
Length: 40949, dtype: int64

In [ ]:
r1 = ((df['views'] - (df['likes'] + df['dislikes'])) / df['views'] ).mean()

In [ ]:
print(r1, 1-r1)

0.9639728697489426 0.036027130251057415

15. Perhatikan grafik perbandingan likes dan views berikut:

Grafik tersebut dipisahkan dengan garis merah menjadi 4 kluster. Tambahkan label kluster pada
dataframe dataset berdasarkan grafik tersebut!

In [ ]:
df2 = df.copy()
df2 = df2.assign(kluster=np.zeros_like(df['likes'].values))

klus1 = df2.query('likes < 10**6 and views < 50* 10**6')
klus2 = df2.query('likes < 10**6 and views >= 50* 10**6')
klus3 = df2.query('likes >= 10**6 and views >= 50* 10**6')
klus4 = df2.query('likes >= 10**6 and views < 50* 10**6')

df2.loc[klus1.index, 'kluster'] = 1
df2.loc[klus2.index, 'kluster'] = 2
df2.loc[klus3.index, 'kluster'] = 3
df2.loc[klus4.index, 'kluster'] = 4

In [ ]:
df2.query('kluster == 1').count()['video_id']

40542

In [ ]:
df2.query('kluster == 2').count()['video_id']

38

In [ ]:
df2.query('kluster == 3').count()['video_id']

139

In [ ]:
df2.query('kluster == 4').count()['video_id']

230